package com.aptrade.desktop.calendar

/** S&P 500 constituent display names (snapshot 2026-07-14, same Wikipedia constituents
 *  table `shared` SP500Symbols was generated from — refresh both together). Desktop-only
 *  by product decision: the Calendar pane shows "SYMBOL  Company Name"; the mobile apps
 *  deliberately show the symbol alone. Missing symbols (user-owned, non-index) simply
 *  render without a name. */
internal val SP500Names: Map<String, String> = mapOf(
    "A" to "Agilent Technologies",
    "AAPL" to "Apple Inc.",
    "ABBV" to "AbbVie",
    "ABNB" to "Airbnb",
    "ABT" to "Abbott Laboratories",
    "ACGL" to "Arch Capital Group",
    "ACN" to "Accenture",
    "ADBE" to "Adobe Inc.",
    "ADI" to "Analog Devices",
    "ADM" to "Archer Daniels Midland",
    "ADP" to "Automatic Data Processing",
    "ADSK" to "Autodesk",
    "AEE" to "Ameren",
    "AEP" to "American Electric Power",
    "AES" to "AES Corporation",
    "AFL" to "Aflac",
    "AIG" to "American International Group",
    "AIZ" to "Assurant",
    "AJG" to "Arthur J. Gallagher & Co.",
    "AKAM" to "Akamai Technologies",
    "ALB" to "Albemarle Corporation",
    "ALGN" to "Align Technology",
    "ALL" to "Allstate",
    "ALLE" to "Allegion",
    "AMAT" to "Applied Materials",
    "AMCR" to "Amcor",
    "AMD" to "Advanced Micro Devices",
    "AME" to "Ametek",
    "AMGN" to "Amgen",
    "AMP" to "Ameriprise Financial",
    "AMT" to "American Tower",
    "AMZN" to "Amazon",
    "ANET" to "Arista Networks",
    "AON" to "Aon plc",
    "AOS" to "A. O. Smith",
    "APA" to "APA Corporation",
    "APD" to "Air Products",
    "APH" to "Amphenol",
    "APO" to "Apollo Global Management",
    "APP" to "AppLovin",
    "APTV" to "Aptiv",
    "ARE" to "Alexandria Real Estate Equities",
    "ARES" to "Ares Management",
    "ATO" to "Atmos Energy",
    "AVB" to "AvalonBay Communities",
    "AVGO" to "Broadcom",
    "AVY" to "Avery Dennison",
    "AWK" to "American Water Works",
    "AXON" to "Axon Enterprise",
    "AXP" to "American Express",
    "AZO" to "AutoZone",
    "BA" to "Boeing",
    "BAC" to "Bank of America",
    "BALL" to "Ball Corporation",
    "BAX" to "Baxter International",
    "BBY" to "Best Buy",
    "BDX" to "Becton Dickinson",
    "BEN" to "Franklin Resources",
    "BF.B" to "Brown–Forman",
    "BG" to "Bunge Global",
    "BIIB" to "Biogen",
    "BKNG" to "Booking Holdings",
    "BKR" to "Baker Hughes",
    "BLDR" to "Builders FirstSource",
    "BLK" to "BlackRock",
    "BMY" to "Bristol Myers Squibb",
    "BNY" to "BNY Mellon",
    "BR" to "Broadridge Financial Solutions",
    "BRK.B" to "Berkshire Hathaway",
    "BRO" to "Brown & Brown",
    "BSX" to "Boston Scientific",
    "BX" to "Blackstone Inc.",
    "BXP" to "BXP, Inc.",
    "C" to "Citigroup",
    "CAH" to "Cardinal Health",
    "CARR" to "Carrier Global",
    "CASY" to "Casey's",
    "CAT" to "Caterpillar Inc.",
    "CB" to "Chubb Limited",
    "CBOE" to "Cboe Global Markets",
    "CBRE" to "CBRE Group",
    "CCI" to "Crown Castle",
    "CCL" to "Carnival Corporation",
    "CDNS" to "Cadence Design Systems",
    "CDW" to "CDW Corporation",
    "CEG" to "Constellation Energy",
    "CF" to "CF Industries",
    "CFG" to "Citizens Financial Group",
    "CHD" to "Church & Dwight",
    "CHRW" to "C.H. Robinson",
    "CHTR" to "Charter Communications",
    "CI" to "Cigna",
    "CIEN" to "Ciena",
    "CINF" to "Cincinnati Financial",
    "CL" to "Colgate-Palmolive",
    "CLX" to "Clorox",
    "CMCSA" to "Comcast",
    "CME" to "CME Group",
    "CMG" to "Chipotle Mexican Grill",
    "CMI" to "Cummins",
    "CMS" to "CMS Energy",
    "CNC" to "Centene Corporation",
    "CNP" to "CenterPoint Energy",
    "COF" to "Capital One",
    "COHR" to "Coherent Corp.",
    "COIN" to "Coinbase",
    "COO" to "Cooper Companies (The)",
    "COP" to "ConocoPhillips",
    "COR" to "Cencora",
    "COST" to "Costco",
    "CPAY" to "Corpay",
    "CPRT" to "Copart",
    "CPT" to "Camden Property Trust",
    "CRH" to "CRH plc",
    "CRL" to "Charles River Laboratories",
    "CRM" to "Salesforce",
    "CRWD" to "CrowdStrike",
    "CSCO" to "Cisco",
    "CSGP" to "CoStar Group",
    "CSX" to "CSX Corporation",
    "CTAS" to "Cintas",
    "CTSH" to "Cognizant",
    "CTVA" to "Corteva",
    "CVNA" to "Carvana",
    "CVS" to "CVS Health",
    "CVX" to "Chevron Corporation",
    "D" to "Dominion Energy",
    "DAL" to "Delta Air Lines",
    "DASH" to "DoorDash",
    "DD" to "DuPont",
    "DDOG" to "Datadog",
    "DE" to "Deere & Company",
    "DECK" to "Deckers Brands",
    "DELL" to "Dell Technologies",
    "DG" to "Dollar General",
    "DGX" to "Quest Diagnostics",
    "DHI" to "D. R. Horton",
    "DHR" to "Danaher Corporation",
    "DIS" to "Walt Disney Company (The)",
    "DLR" to "Digital Realty",
    "DLTR" to "Dollar Tree",
    "DOC" to "Healthpeak Properties",
    "DOV" to "Dover Corporation",
    "DOW" to "Dow Inc.",
    "DPZ" to "Domino's",
    "DRI" to "Darden Restaurants",
    "DTE" to "DTE Energy",
    "DUK" to "Duke Energy",
    "DVA" to "DaVita",
    "DVN" to "Devon Energy",
    "DXCM" to "Dexcom",
    "EA" to "Electronic Arts",
    "EBAY" to "eBay Inc.",
    "ECHO" to "EchoStar",
    "ECL" to "Ecolab",
    "ED" to "Consolidated Edison",
    "EFX" to "Equifax",
    "EG" to "Everest Group",
    "EIX" to "Edison International",
    "EL" to "Estée Lauder Companies (The)",
    "ELV" to "Elevance Health",
    "EME" to "Emcor",
    "EMR" to "Emerson Electric",
    "EOG" to "EOG Resources",
    "EQIX" to "Equinix",
    "EQR" to "Equity Residential",
    "EQT" to "EQT Corporation",
    "ERIE" to "Erie Indemnity",
    "ES" to "Eversource Energy",
    "ESS" to "Essex Property Trust",
    "ETN" to "Eaton Corporation",
    "ETR" to "Entergy",
    "EVRG" to "Evergy",
    "EW" to "Edwards Lifesciences",
    "EXC" to "Exelon",
    "EXE" to "Expand Energy",
    "EXPD" to "Expeditors International",
    "EXPE" to "Expedia Group",
    "EXR" to "Extra Space Storage",
    "F" to "Ford Motor Company",
    "FANG" to "Diamondback Energy",
    "FAST" to "Fastenal",
    "FCX" to "Freeport-McMoRan",
    "FDS" to "FactSet",
    "FDX" to "FedEx",
    "FDXF" to "FedEx Freight",
    "FE" to "FirstEnergy",
    "FFIV" to "F5, Inc.",
    "FICO" to "Fair Isaac",
    "FIS" to "Fidelity National Information Services",
    "FISV" to "Fiserv",
    "FITB" to "Fifth Third Bancorp",
    "FIX" to "Comfort Systems USA",
    "FLEX" to "Flex Ltd.",
    "FOX" to "Fox Corporation",
    "FOXA" to "Fox Corporation",
    "FRT" to "Federal Realty Investment Trust",
    "FSLR" to "First Solar",
    "FTNT" to "Fortinet",
    "FTV" to "Fortive",
    "GD" to "General Dynamics",
    "GDDY" to "GoDaddy",
    "GE" to "GE Aerospace",
    "GEHC" to "GE HealthCare",
    "GEN" to "Gen Digital",
    "GEV" to "GE Vernova",
    "GILD" to "Gilead Sciences",
    "GIS" to "General Mills",
    "GL" to "Globe Life",
    "GLW" to "Corning Inc.",
    "GM" to "General Motors",
    "GNRC" to "Generac",
    "GOOG" to "Alphabet Inc.",
    "GOOGL" to "Alphabet Inc.",
    "GPC" to "Genuine Parts Company",
    "GPN" to "Global Payments",
    "GRMN" to "Garmin",
    "GS" to "Goldman Sachs",
    "GWW" to "W. W. Grainger",
    "HAL" to "Halliburton",
    "HAS" to "Hasbro",
    "HBAN" to "Huntington Bancshares",
    "HCA" to "HCA Healthcare",
    "HD" to "Home Depot (The)",
    "HIG" to "Hartford (The)",
    "HII" to "Huntington Ingalls Industries",
    "HLT" to "Hilton Worldwide",
    "HON" to "Honeywell Technologies",
    "HONA" to "Honeywell Aerospace",
    "HOOD" to "Robinhood Markets",
    "HPE" to "Hewlett Packard Enterprise",
    "HPQ" to "HP Inc.",
    "HRL" to "Hormel Foods",
    "HSIC" to "Henry Schein",
    "HST" to "Host Hotels & Resorts",
    "HSY" to "Hershey Company (The)",
    "HUBB" to "Hubbell Incorporated",
    "HUM" to "Humana",
    "HWM" to "Howmet Aerospace",
    "IBKR" to "Interactive Brokers",
    "IBM" to "IBM",
    "ICE" to "Intercontinental Exchange",
    "IDXX" to "Idexx Laboratories",
    "IEX" to "IDEX Corporation",
    "IFF" to "International Flavors & Fragrances",
    "INCY" to "Incyte",
    "INTC" to "Intel",
    "INTU" to "Intuit",
    "INVH" to "Invitation Homes",
    "IP" to "International Paper",
    "IQV" to "IQVIA",
    "IR" to "Ingersoll Rand",
    "IRM" to "Iron Mountain",
    "ISRG" to "Intuitive Surgical",
    "IT" to "Gartner",
    "ITW" to "Illinois Tool Works",
    "IVZ" to "Invesco",
    "J" to "Jacobs Solutions",
    "JBHT" to "J.B. Hunt",
    "JBL" to "Jabil",
    "JCI" to "Johnson Controls",
    "JKHY" to "Jack Henry & Associates",
    "JNJ" to "Johnson & Johnson",
    "JPM" to "JPMorgan Chase",
    "KDP" to "Keurig Dr Pepper",
    "KEY" to "KeyCorp",
    "KEYS" to "Keysight Technologies",
    "KHC" to "Kraft Heinz",
    "KIM" to "Kimco Realty",
    "KKR" to "KKR & Co.",
    "KLAC" to "KLA Corporation",
    "KMB" to "Kimberly-Clark",
    "KMI" to "Kinder Morgan",
    "KO" to "Coca-Cola Company (The)",
    "KR" to "Kroger",
    "KVUE" to "Kenvue",
    "L" to "Loews Corporation",
    "LDOS" to "Leidos",
    "LEN" to "Lennar",
    "LH" to "Labcorp",
    "LHX" to "L3Harris",
    "LII" to "Lennox International",
    "LIN" to "Linde plc",
    "LITE" to "Lumentum",
    "LLY" to "Lilly (Eli)",
    "LMT" to "Lockheed Martin",
    "LNT" to "Alliant Energy",
    "LOW" to "Lowe's",
    "LRCX" to "Lam Research",
    "LULU" to "Lululemon Athletica",
    "LUV" to "Southwest Airlines",
    "LVS" to "Las Vegas Sands",
    "LYB" to "LyondellBasell",
    "LYV" to "Live Nation Entertainment",
    "MA" to "Mastercard",
    "MAA" to "Mid-America Apartment Communities",
    "MAR" to "Marriott International",
    "MAS" to "Masco",
    "MCD" to "McDonald's",
    "MCHP" to "Microchip Technology",
    "MCK" to "McKesson Corporation",
    "MCO" to "Moody's Corporation",
    "MDLZ" to "Mondelez International",
    "MDT" to "Medtronic",
    "MET" to "MetLife",
    "META" to "Meta Platforms",
    "MGM" to "MGM Resorts",
    "MKC" to "McCormick & Company",
    "MLM" to "Martin Marietta Materials",
    "MMM" to "3M",
    "MNST" to "Monster Beverage",
    "MO" to "Altria",
    "MOS" to "Mosaic Company (The)",
    "MPC" to "Marathon Petroleum",
    "MPWR" to "Monolithic Power Systems",
    "MRK" to "Merck & Co.",
    "MRNA" to "Moderna",
    "MRSH" to "Marsh McLennan",
    "MRVL" to "Marvell Technology",
    "MS" to "Morgan Stanley",
    "MSCI" to "MSCI Inc.",
    "MSFT" to "Microsoft",
    "MSI" to "Motorola Solutions",
    "MTB" to "M&T Bank",
    "MTD" to "Mettler Toledo",
    "MU" to "Micron Technology",
    "NCLH" to "Norwegian Cruise Line Holdings",
    "NDAQ" to "Nasdaq, Inc.",
    "NDSN" to "Nordson Corporation",
    "NEE" to "NextEra Energy",
    "NEM" to "Newmont",
    "NFLX" to "Netflix",
    "NI" to "NiSource",
    "NKE" to "Nike, Inc.",
    "NOC" to "Northrop Grumman",
    "NOW" to "ServiceNow",
    "NRG" to "NRG Energy",
    "NSC" to "Norfolk Southern",
    "NTAP" to "NetApp",
    "NTRS" to "Northern Trust",
    "NUE" to "Nucor",
    "NVDA" to "Nvidia",
    "NVR" to "NVR, Inc.",
    "NWS" to "News Corp",
    "NWSA" to "News Corp",
    "NXPI" to "NXP Semiconductors",
    "O" to "Realty Income",
    "ODFL" to "Old Dominion",
    "OKE" to "Oneok",
    "OMC" to "Omnicom Group",
    "ON" to "ON Semiconductor",
    "ORCL" to "Oracle Corporation",
    "ORLY" to "O’Reilly Automotive",
    "OTIS" to "Otis Worldwide",
    "OXY" to "Occidental Petroleum",
    "PANW" to "Palo Alto Networks",
    "PAYX" to "Paychex",
    "PCAR" to "Paccar",
    "PCG" to "PG&E Corporation",
    "PEG" to "Public Service Enterprise Group",
    "PEP" to "PepsiCo",
    "PFE" to "Pfizer",
    "PFG" to "Principal Financial Group",
    "PG" to "Procter & Gamble",
    "PGR" to "Progressive Corporation",
    "PH" to "Parker Hannifin",
    "PHM" to "PulteGroup",
    "PKG" to "Packaging Corporation of America",
    "PLD" to "Prologis",
    "PLTR" to "Palantir Technologies",
    "PM" to "Philip Morris International",
    "PNC" to "PNC Financial Services",
    "PNR" to "Pentair",
    "PNW" to "Pinnacle West Capital",
    "PODD" to "Insulet Corporation",
    "PPG" to "PPG Industries",
    "PPL" to "PPL Corporation",
    "PRU" to "Prudential Financial",
    "PSA" to "Public Storage",
    "PSKY" to "Paramount Skydance Corporation",
    "PSX" to "Phillips 66",
    "PTC" to "PTC Inc.",
    "PWR" to "Quanta Services",
    "PYPL" to "PayPal",
    "Q" to "Qnity Electronics",
    "QCOM" to "Qualcomm",
    "RCL" to "Royal Caribbean Group",
    "REG" to "Regency Centers",
    "REGN" to "Regeneron Pharmaceuticals",
    "RF" to "Regions Financial Corporation",
    "RJF" to "Raymond James Financial",
    "RL" to "Ralph Lauren Corporation",
    "RMD" to "ResMed",
    "ROK" to "Rockwell Automation",
    "ROL" to "Rollins, Inc.",
    "ROP" to "Roper Technologies",
    "ROST" to "Ross Stores",
    "RSG" to "Republic Services",
    "RTX" to "RTX Corporation",
    "RVTY" to "Revvity",
    "SBAC" to "SBA Communications",
    "SBUX" to "Starbucks",
    "SCHW" to "Charles Schwab Corporation",
    "SHW" to "Sherwin-Williams",
    "SJM" to "J.M. Smucker Company (The)",
    "SLB" to "Schlumberger",
    "SMCI" to "Supermicro",
    "SNA" to "Snap-on",
    "SNDK" to "Sandisk",
    "SNPS" to "Synopsys",
    "SO" to "Southern Company",
    "SOLV" to "Solventum",
    "SPG" to "Simon Property Group",
    "SPGI" to "S&P Global",
    "SRE" to "Sempra",
    "STE" to "Steris",
    "STLD" to "Steel Dynamics",
    "STT" to "State Street Corporation",
    "STX" to "Seagate Technology",
    "STZ" to "Constellation Brands",
    "SW" to "Smurfit Westrock",
    "SWK" to "Stanley Black & Decker",
    "SWKS" to "Skyworks Solutions",
    "SYF" to "Synchrony Financial",
    "SYK" to "Stryker Corporation",
    "SYY" to "Sysco",
    "T" to "AT&T",
    "TAP" to "Molson Coors Beverage Company",
    "TDG" to "TransDigm Group",
    "TDY" to "Teledyne Technologies",
    "TECH" to "Bio-Techne",
    "TEL" to "TE Connectivity",
    "TER" to "Teradyne",
    "TFC" to "Truist Financial",
    "TGT" to "Target Corporation",
    "TJX" to "TJX Companies",
    "TKO" to "TKO Group Holdings",
    "TMO" to "Thermo Fisher Scientific",
    "TMUS" to "T-Mobile US",
    "TPL" to "Texas Pacific Land Corporation",
    "TPR" to "Tapestry, Inc.",
    "TRGP" to "Targa Resources",
    "TRMB" to "Trimble Inc.",
    "TROW" to "T. Rowe Price",
    "TRV" to "Travelers Companies (The)",
    "TSCO" to "Tractor Supply",
    "TSLA" to "Tesla, Inc.",
    "TSN" to "Tyson Foods",
    "TT" to "Trane Technologies",
    "TTD" to "Trade Desk (The)",
    "TTWO" to "Take-Two Interactive",
    "TXN" to "Texas Instruments",
    "TXT" to "Textron",
    "TYL" to "Tyler Technologies",
    "UAL" to "United Airlines Holdings",
    "UBER" to "Uber",
    "UDR" to "UDR, Inc.",
    "UHS" to "Universal Health Services",
    "ULTA" to "Ulta Beauty",
    "UNH" to "UnitedHealth Group",
    "UNP" to "Union Pacific Corporation",
    "UPS" to "United Parcel Service",
    "URI" to "United Rentals",
    "USB" to "U.S. Bancorp",
    "V" to "Visa Inc.",
    "VEEV" to "Veeva Systems",
    "VICI" to "Vici Properties",
    "VLO" to "Valero Energy",
    "VLTO" to "Veralto",
    "VMC" to "Vulcan Materials Company",
    "VRSK" to "Verisk Analytics",
    "VRSN" to "Verisign",
    "VRT" to "Vertiv",
    "VRTX" to "Vertex Pharmaceuticals",
    "VST" to "Vistra Corp",
    "VTR" to "Ventas",
    "VTRS" to "Viatris",
    "VZ" to "Verizon",
    "WAB" to "Wabtec",
    "WAT" to "Waters Corporation",
    "WBD" to "Warner Bros. Discovery",
    "WDAY" to "Workday, Inc.",
    "WDC" to "Western Digital",
    "WEC" to "WEC Energy Group",
    "WELL" to "Welltower",
    "WFC" to "Wells Fargo",
    "WM" to "Waste Management",
    "WMB" to "Williams Companies",
    "WMT" to "Walmart",
    "WRB" to "W. R. Berkley Corporation",
    "WSM" to "Williams-Sonoma, Inc.",
    "WST" to "West Pharmaceutical Services",
    "WTW" to "Willis Towers Watson",
    "WY" to "Weyerhaeuser",
    "WYNN" to "Wynn Resorts",
    "XEL" to "Xcel Energy",
    "XOM" to "ExxonMobil",
    "XYL" to "Xylem Inc.",
    "XYZ" to "Block, Inc.",
    "YUM" to "Yum! Brands",
    "ZBH" to "Zimmer Biomet",
    "ZBRA" to "Zebra Technologies",
    "ZTS" to "Zoetis",
)
